// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function AttachTarget(arg1:string,arg2:string):Promise<api.Response_cdpnetool_pkg_api_EmptyData_>;

export function CleanupEventHistory(arg1:number):Promise<api.Response_cdpnetool_pkg_api_EmptyData_>;

export function CloseBrowser():Promise<api.Response_cdpnetool_pkg_api_EmptyData_>;

export function CreateNewConfig(arg1:string):Promise<api.Response_cdpnetool_internal_gui_NewConfigData_>;

export function DeleteConfig(arg1:number):Promise<api.Response_cdpnetool_pkg_api_EmptyData_>;

export function DetachTarget(arg1:string,arg2:string):Promise<api.Response_cdpnetool_pkg_api_EmptyData_>;

export function DisableInterception(arg1:string):Promise<api.Response_cdpnetool_pkg_api_EmptyData_>;

export function EnableInterception(arg1:string):Promise<api.Response_cdpnetool_pkg_api_EmptyData_>;

export function ExportConfig(arg1:string,arg2:string):Promise<api.Response_cdpnetool_pkg_api_EmptyData_>;

export function GenerateNewRule(arg1:string,arg2:number):Promise<api.Response_cdpnetool_internal_gui_NewRuleData_>;

export function GetActiveConfig():Promise<api.Response_cdpnetool_internal_gui_ConfigData_>;

export function GetAllSettings():Promise<api.Response_cdpnetool_internal_gui_SettingsData_>;

export function GetBrowserStatus():Promise<api.Response_cdpnetool_internal_gui_BrowserData_>;

export function GetConfig(arg1:number):Promise<api.Response_cdpnetool_internal_gui_ConfigData_>;

export function GetCurrentSession():Promise<api.Response_cdpnetool_internal_gui_SessionData_>;

export function GetRuleStats(arg1:string):Promise<api.Response_cdpnetool_internal_gui_StatsData_>;

export function GetSetting(arg1:string):Promise<api.Response_cdpnetool_internal_gui_SettingData_>;

export function GetVersion():Promise<api.Response_cdpnetool_internal_gui_VersionData_>;

export function ImportConfig(arg1:string):Promise<api.Response_cdpnetool_internal_gui_ConfigData_>;

export function LaunchBrowser(arg1:boolean):Promise<api.Response_cdpnetool_internal_gui_BrowserData_>;

export function ListConfigs():Promise<api.Response_cdpnetool_internal_gui_ConfigListData_>;

export function ListTargets(arg1:string):Promise<api.Response_cdpnetool_internal_gui_TargetListData_>;

export function LoadActiveConfigToSession():Promise<api.Response_cdpnetool_pkg_api_EmptyData_>;

export function LoadRules(arg1:string,arg2:string):Promise<api.Response_cdpnetool_pkg_api_EmptyData_>;

export function QueryMatchedEventHistory(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:number,arg8:number):Promise<api.Response_cdpnetool_internal_gui_EventHistoryData_>;

export function RenameConfig(arg1:number,arg2:string):Promise<api.Response_cdpnetool_pkg_api_EmptyData_>;

export function SaveConfig(arg1:number,arg2:string):Promise<api.Response_cdpnetool_internal_gui_ConfigData_>;

export function SetActiveConfig(arg1:number):Promise<api.Response_cdpnetool_pkg_api_EmptyData_>;

export function SetCollectionMode(arg1:string,arg2:boolean):Promise<api.Response_cdpnetool_pkg_api_EmptyData_>;

export function SetDirty(arg1:boolean):Promise<void>;

export function SetMultipleSettings(arg1:string):Promise<api.Response_cdpnetool_pkg_api_EmptyData_>;

export function SetSetting(arg1:string,arg2:string):Promise<api.Response_cdpnetool_pkg_api_EmptyData_>;

export function StartSession(arg1:string):Promise<api.Response_cdpnetool_internal_gui_SessionData_>;

export function StopSession(arg1:string):Promise<api.Response_cdpnetool_pkg_api_EmptyData_>;
